name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build and test
      run: |
        npm ci
        npm run build
        npm run lint
        npm run test
      env:
        CI: true
    - name: Generate Page
      if: github.ref == 'master'
      run: npm run generate
    - name: GitHub Pages Deploy
      if: github.ref == 'master'
      uses: maxheld83/ghpages@v0.2.1
      env:
        GH_PAT: ${{ GH_PAT }}
        BUILD_DIR: 'dist/'
